In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv('/content/WineQT.csv')

In [4]:
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [5]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4

In [6]:
df.tail()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [7]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
count,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,8.311111,0.531339,0.268364,2.532152,0.086933,15.615486,45.914698,0.996730,3.311015,0.657708,10.442111,5.657043,804.969379
std,1.747595,0.179633,0.196686,1.355917,0.047267,10.250486,32.782130,0.001925,0.156664,0.170399,1.082196,0.805824,463.997116
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000,0.000000
25%,7.100000,0.392500,0.090000,1.900000,0.070000,7.000000,21.000000,0.995570,3.205000,0.550000,9.500000,5.000000,411.000000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,13.000000,37.000000,0.996680,3.310000,0.620000,10.200000,6.000000,794.000000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,61.000000,0.997845,3.400000,0.730000,11.100000,6.000000,1209.500000
max,15.900000,1.580000,1.000000,15.500000,0.611000,68.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000,1597.000000

In [8]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
Id                        int64
dtype: object

In [9]:
df.shape

(1143, 13)

In [11]:
#ENCODE CATEGORICAL -> NUMERIC

In [14]:
from sklearn.preprocessing import LabelEncoder

le = {} #create empty dictionary
df_enc = df.copy() #here we just cop our original data
for col in df.columns: #it convert into the text using loop through of the column
    le[col] = LabelEncoder() #now create new label for current data
    df_enc[col] = le[col].fit_transform(df[col])

In [15]:
df_enc

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,25,74,0,10,39,9,28,305,62,17,10,2,0
1,29,110,0,20,61,23,61,246,31,29,15,2,1
2,29,86,4,17,55,13,48,260,37,26,15,2,2
3,62,12,56,10,38,15,54,315,27,19,15,3,3
4,25,74,0,10,39,9,28,305,62,17,10,2,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,14,40,13,17,39,27,34,166,53,36,30,3,1138
1139,19,58,8,10,31,26,32,226,53,43,11,3,1139
1140,13,54,8,11,53,30,38,105,56,19,24,2,1140
1141,10,45,10,15,25,38,45,119,63,37,33,3,1141
1142,10,63,12,11,38,30,38,145,68,32,21,2,1142

In [16]:
#FEATURES & TARGET

In [18]:
# Use the actual columns from the Wine Quality dataset
x = df_enc.drop(columns=['Id', 'quality'])
y = df_enc['quality']

In [19]:
x

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,25,74,0,10,39,9,28,305,62,17,10
1,29,110,0,20,61,23,61,246,31,29,15
2,29,86,4,17,55,13,48,260,37,26,15
3,62,12,56,10,38,15,54,315,27,19,15
4,25,74,0,10,39,9,28,305,62,17,10
...,...,...,...,...,...,...,...,...,...,...,...
1138,14,40,13,17,39,27,34,166,53,36,30
1139,19,58,8,10,31,26,32,226,53,43,11
1140,13,54,8,11,53,30,38,105,56,19,24
1141,10,45,10,15,25,38,45,119,63,37,33
1142,10,63,12,11,38,30,38,145,68,32,21

In [20]:
y

0       2
1       2
2       2
3       3
4       2
       ..
1138    3
1139    3
1140    2
1141    3
1142    2
Name: quality, Length: 1143, dtype: int64

In [22]:
from sklearn.naive_bayes import CategoricalNB

model = CategoricalNB() #apply model
model.fit(x,y) #fit the data

CategoricalNB()

In [30]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64